
steps:
  # Step 1: Compile the Go application
  - name: 'gcr.io/cloud-builders/go'
    env: ['GOPATH=/gopath']
    args: ['build', '-o', 'main', 'main.go']

  # Step 2: Build the Docker image for the Go application
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-repository/sample-app:v1.0', '.']

  # Step 3: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-repository/sample-app:v1.0']

  # Step 4: Deploy to the production namespace
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'prod/deployment.yaml', '--namespace=prod']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-east4'
      - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'
