apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prod-app
  template:
    metadata:
      labels:
        app: prod-app
    spec:
      containers:
      - name: prod-container
        image: gcr.io/$PROJECT_ID/my-repository/hello-cloudbuild-prod:v1.0
        ports:
        - containerPort: 8080
